# Generated by Django 2.2.1 on 2020-03-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name_plural': 'Records'},
        ),
    ]
