# Generated by Django 2.2.1 on 2020-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200321_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='education',
            new_name='course',
        ),
        migrations.RemoveField(
            model_name='records',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='records',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='records',
            name='occupation',
        ),
        migrations.AddField(
            model_name='records',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
